### ISSUE TITLE
Compilation documentation for libsodium

### ISSUE THREAD

**Issue by GabrielHare** [cxxpxr/monke#1]
Can you please document / link your build project for [Sodium](https://github.com/jedisct1/libsodium), including the commit hash?

Why: when using Monke I was required to switch to .NET 4.x because Sodium uses System.AppDomain.DefineDynamicAssembly which is not supported in .NET Standard 2.0. Looking through in the [Sodium](https://doc.libsodium.org/bindings_for_other_languages) project there seems to be more than one .NET support library.

Also why: It just feels better to start from open source, especially for security libraries.

**Comment by GabrielHare** [comment]
Possibly related to this: running UnityEditor 2019.4.36f1 in Ubuntu 20,04, I can build and run using Monke... but when I play in the editor I get the follow error complaining that libsodium cannot be found. (However, the same project both builds and plays in editor in macOS and Windows10)

> DllNotFoundException: libsodium
Sodium.PublicKeyBox.GenerateKeyPair () (at <fc18acf0ff864dd7bdbcc455b392289d>:0)
MonkeCore.Monke.GenerateInitialKeyPair () (at Assets/Mirror/Runtime/Transports/MonkeTransport/Monke.cs:76)
MonkeCore.Monke.ClientConnect (System.String address) (at Assets/Mirror/Runtime/Transports/MonkeTransport/Monke.cs:191)

After confirming that Plugins/Linux/libsodium.so correctly marked for use with Linux x86_64 in the editor settings as well as the standalone settings, I followed the invocation calls through the dll, arriving at the DynamicInvoke definition. This seems like a huge amount of indirection, where I would have expected a simple DLLImport.

NOTE: As you can see in the log, Monke has been put in a namespace, and the source code has been moved in to the Mirror project directory.

**Comment by cxxpxr** [comment]
Hi, I no longer maintain this repository, please refer to this fork instead: https://github.com/JesusLuvsYooh/monke
