### ISSUE TITLE
Subtract the header size from the max packet size

### ISSUE THREAD

**Issue by GabrielHare** [cxxpxr/monke#2]
The size increase from securing a packet is [claimed to be 16 bytes](https://github.com/JesusLuvsYooh/monke).
So the method GetMaxPacketSize should be adjusted accordingly. Probably something like:
`public override int GetMaxPacketSize(int channelId = 0) => CommunicationTransport.GetMaxPacketSize(channelId) - 16;`

In the case of the Ignorance transport exceeding the allowed packet size is nicely handled by falling back to reliable fragmented, but I don't know about other transports.

**Comment by cxxpxr** [comment]
Hi, I no longer maintain this repository, please refer to this fork instead: https://github.com/JesusLuvsYooh/monke
